--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/nhanaz-pm-pl/AdvancedRules
build-by-default: true
branches:
- master
projects:
  AdvancedRules:
    path: ""
    libs:
    - src: dktapps-pm-pl/pmforms/pmforms
      version: ^2.0.0
...
