---
name: AdvancedRules
version: 1.0.2+dev
main: NhanAZ\AdvancedRules\Main
api: 5.0.0
author: NhanAZ
website: https://github.com/NhanAZ
description: "Get players who join your server for the first time to accept the server rules with AdvancedRules."
...
